theme: minima
title: My Portfolio
author: Mariana Ubiali Leite
email: mul2000@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio for Mariana Ubiali Leite

# social links
twitter_username: my-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  mul2000 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
